from __future__ import annotations


class ArithmeticException(Exception):
    pass
